// countries.js - Full list with local flag SVGs

const countries = [
  { short: "AF", code: "+93" },
  { short: "AL", code: "+355" },
  { short: "DZ", code: "+213" },
  { short: "AS", code: "+1-684" },
  { short: "AD", code: "+376" },
  { short: "AO", code: "+244" },
  { short: "AI", code: "+1-264" },
  { short: "AG", code: "+1-268" },
  { short: "AR", code: "+54" },
  { short: "AM", code: "+374" },
  { short: "AW", code: "+297" },
  { short: "AU", code: "+61" },
  { short: "AT", code: "+43" },
  { short: "AZ", code: "+994" },
  { short: "BS", code: "+1-242" },
  { short: "BH", code: "+973" },
  { short: "BD", code: "+880" },
  { short: "BB", code: "+1-246" },
  { short: "BY", code: "+375" },
  { short: "BE", code: "+32" },
  { short: "BZ", code: "+501" },
  { short: "BJ", code: "+229" },
  { short: "BM", code: "+1-441" },
  { short: "BT", code: "+975" },
  { short: "BO", code: "+591" },
  { short: "BA", code: "+387" },
  { short: "BW", code: "+267" },
  { short: "BR", code: "+55" },
  { short: "IO", code: "+246" },
  { short: "VG", code: "+1-284" },
  { short: "BN", code: "+673" },
  { short: "BG", code: "+359" },
  { short: "BF", code: "+226" },
  { short: "BI", code: "+257" },
  { short: "KH", code: "+855" },
  { short: "CM", code: "+237" },
  { short: "CA", code: "+1" },
  { short: "CV", code: "+238" },
  { short: "KY", code: "+1-345" },
  { short: "CF", code: "+236" },
  { short: "TD", code: "+235" },
  { short: "CL", code: "+56" },
  { short: "CN", code: "+86" },
  { short: "CX", code: "+61" },
  { short: "CC", code: "+61" },
  { short: "CO", code: "+57" },
  { short: "KM", code: "+269" },
  { short: "CK", code: "+682" },
  { short: "CR", code: "+506" },
  { short: "HR", code: "+385" },
  { short: "CU", code: "+53" },
  { short: "CW", code: "+599" },
  { short: "CY", code: "+357" },
  { short: "CZ", code: "+420" },
  { short: "CD", code: "+243" },
  { short: "DK", code: "+45" },
  { short: "DJ", code: "+253" },
  { short: "DM", code: "+1-767" },
  { short: "DO", code: "+1-809" },
  { short: "EC", code: "+593" },
  { short: "EG", code: "+20" },
  { short: "SV", code: "+503" },
  { short: "GQ", code: "+240" },
  { short: "ER", code: "+291" },
  { short: "EE", code: "+372" },
  { short: "ET", code: "+251" },
  { short: "FK", code: "+500" },
  { short: "FO", code: "+298" },
  { short: "FJ", code: "+679" },
  { short: "FI", code: "+358" },
  { short: "FR", code: "+33" },
  { short: "GF", code: "+594" },
  { short: "PF", code: "+689" },
  { short: "GA", code: "+241" },
  { short: "GM", code: "+220" },
  { short: "GE", code: "+995" },
  { short: "DE", code: "+49" },
  { short: "GH", code: "+233" },
  { short: "GI", code: "+350" },
  { short: "GR", code: "+30" },
  { short: "GL", code: "+299" },
  { short: "GD", code: "+1-473" },
  { short: "GP", code: "+590" },
  { short: "GU", code: "+1-671" },
  { short: "GT", code: "+502" },
  { short: "GG", code: "+44" },
  { short: "GN", code: "+224" },
  { short: "GW", code: "+245" },
  { short: "GY", code: "+592" },
  { short: "HT", code: "+509" },
  { short: "HN", code: "+504" },
  { short: "HK", code: "+852" },
  { short: "HU", code: "+36" },
  { short: "IS", code: "+354" },
  { short: "IN", code: "+91" },
  { short: "ID", code: "+62" },
  { short: "IR", code: "+98" },
  { short: "IQ", code: "+964" },
  { short: "IE", code: "+353" },
  { short: "IM", code: "+44" },
  { short: "IL", code: "+972" },
  { short: "IT", code: "+39" },
  { short: "CI", code: "+225" },
  { short: "JM", code: "+1-876" },
  { short: "JP", code: "+81" },
  { short: "JE", code: "+44" },
  { short: "JO", code: "+962" },
  { short: "KZ", code: "+7" },
  { short: "KE", code: "+254" },
  { short: "KI", code: "+686" },
  { short: "XK", code: "+383" },
  { short: "KW", code: "+965" },
  { short: "KG", code: "+996" },
  { short: "LA", code: "+856" },
  { short: "LV", code: "+371" },
  { short: "LB", code: "+961" },
  { short: "LS", code: "+266" },
  { short: "LR", code: "+231" },
  { short: "LY", code: "+218" },
  { short: "LI", code: "+423" },
  { short: "LT", code: "+370" },
  { short: "LU", code: "+352" },
  { short: "MO", code: "+853" },
  { short: "MK", code: "+389" },
  { short: "MG", code: "+261" },
  { short: "MW", code: "+265" },
  { short: "MY", code: "+60" },
  { short: "MV", code: "+960" },
  { short: "ML", code: "+223" },
  { short: "MT", code: "+356" },
  { short: "MH", code: "+692" },
  { short: "MQ", code: "+596" },
  { short: "MR", code: "+222" },
  { short: "MU", code: "+230" },
  { short: "YT", code: "+262" },
  { short: "MX", code: "+52" },
  { short: "FM", code: "+691" },
  { short: "MD", code: "+373" },
  { short: "MC", code: "+377" },
  { short: "MN", code: "+976" },
  { short: "ME", code: "+382" },
  { short: "MS", code: "+1-664" },
  { short: "MA", code: "+212" },
  { short: "MZ", code: "+258" },
  { short: "MM", code: "+95" },
  { short: "NA", code: "+264" },
  { short: "NR", code: "+674" },
  { short: "NP", code: "+977" },
  { short: "NL", code: "+31" },
  { short: "NC", code: "+687" },
  { short: "NZ", code: "+64" },
  { short: "NI", code: "+505" },
  { short: "NE", code: "+227" },
  { short: "NG", code: "+234" },
  { short: "NU", code: "+683" },
  { short: "NF", code: "+672" },
  { short: "KP", code: "+850" },
  { short: "NO", code: "+47" },
  { short: "OM", code: "+968" },
  { short: "PK", code: "+92" },
  { short: "PW", code: "+680" },
  { short: "PS", code: "+970" },
  { short: "PA", code: "+507" },
  { short: "PG", code: "+675" },
  { short: "PY", code: "+595" },
  { short: "PE", code: "+51" },
  { short: "PH", code: "+63" },
  { short: "PL", code: "+48" },
  { short: "PT", code: "+351" },
  { short: "PR", code: "+1-787" },
  { short: "QA", code: "+974" },
  { short: "CG", code: "+242" },
  { short: "RE", code: "+262" },
  { short: "RO", code: "+40" },
  { short: "RU", code: "+7" },
  { short: "RW", code: "+250" },
  { short: "BL", code: "+590" },
  { short: "SH", code: "+290" },
  { short: "KN", code: "+1-869" },
  { short: "LC", code: "+1-758" },
  { short: "MF", code: "+590" },
  { short: "PM", code: "+508" },
  { short: "VC", code: "+1-784" },
  { short: "WS", code: "+685" },
  { short: "SM", code: "+378" },
  { short: "ST", code: "+239" },
  { short: "SA", code: "+966" },
  { short: "SN", code: "+221" },
  { short: "RS", code: "+381" },
  { short: "SC", code: "+248" },
  { short: "SL", code: "+232" },
  { short: "SG", code: "+65" },
  { short: "SX", code: "+1-721" },
  { short: "SK", code: "+421" },
  { short: "SI", code: "+386" },
  { short: "SB", code: "+677" },
  { short: "SO", code: "+252" },
  { short: "ZA", code: "+27" },
  { short: "GS", code: "+500" },
  { short: "KR", code: "+82" },
  { short: "SS", code: "+211" },
  { short: "ES", code: "+34" },
  { short: "LK", code: "+94" },
  { short: "SD", code: "+249" },
  { short: "SR", code: "+597" },
  { short: "SZ", code: "+268" },
  { short: "SE", code: "+46" },
  { short: "CH", code: "+41" },
  { short: "SY", code: "+963" },
  { short: "TW", code: "+886" },
  { short: "TJ", code: "+992" },
  { short: "TZ", code: "+255" },
  { short: "TH", code: "+66" },
  { short: "TL", code: "+670" },
  { short: "TG", code: "+228" },
  { short: "TK", code: "+690" },
  { short: "TO", code: "+676" },
  { short: "TT", code: "+1-868" },
  { short: "TN", code: "+216" },
  { short: "TR", code: "+90" },
  { short: "TM", code: "+993" },
  { short: "TC", code: "+1-649" },
  { short: "TV", code: "+688" },
  { short: "UG", code: "+256" },
  { short: "UA", code: "+380" },
  { short: "AE", code: "+971" },
  { short: "GB", code: "+44" },
  { short: "US", code: "+1" },
  { short: "UY", code: "+598" },
  { short: "UZ", code: "+998" },
  { short: "VU", code: "+678" },
  { short: "VA", code: "+39" },
  { short: "VE", code: "+58" },
  { short: "VN", code: "+84" },
  { short: "VI", code: "+1-340" },
  { short: "WF", code: "+681" },
  { short: "EH", code: "+212" },
  { short: "YE", code: "+967" },
  { short: "ZM", code: "+260" },
  { short: "ZW", code: "+263" }
];

function populateCountries(selectId) {
  const select = document.getElementById(selectId);

  // Build country options
  countries.forEach(c => {
    const option = document.createElement("option");
    option.value = c.code;
    option.textContent = `${c.code} ${c.short}`;
    option.setAttribute("data-flag", `assets/1x1/${c.short.toLowerCase()}.svg`);
    select.appendChild(option);
  });

  // Default = UAE
  select.value = "+971";

  if (typeof $ !== "undefined" && $.fn.niceSelect) {
    $(select).niceSelect("destroy").niceSelect();
    const dropdown = $(select).next(".nice-select");

    // Helper → add flags to list + current
    function applyFlags() {
      // Dropdown list flags
      dropdown.find(".list li").each(function (i) {
        const flag = $(select).find("option").eq(i).data("flag");
        if (flag) {
          $(this).css({
            "padding-left": "32px",
            "background-image": `url(${flag})`,
            "background-repeat": "no-repeat",
            "background-position": "8px center",
            "background-size": "20px 20px"
          });
        }
      });

      // Current selected flag
      const current = dropdown.find(".current");
      const selectedFlag = $(select).find("option:selected").data("flag");
      if (selectedFlag) {
        current.css({
          "padding-left": "32px",
          "background-image": `url(${selectedFlag})`,
          "background-repeat": "no-repeat",
          "background-position": "8px center",
          "background-size": "20px 20px"
        });
      }
    }

    // Run once
    applyFlags();

    // Update flag on change
    $(select).on("change", applyFlags);
  }
}

document.addEventListener("DOMContentLoaded", () => {
  populateCountries("countryCode");
});
